---
name: Build and test

on:
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        if: "${{ steps.extract_branch.outputs.branch != 'release-please--branches--main' }}"
        with:
          node-version: 18.19.0

      - uses: pnpm/action-setup@v3

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Typecheck
        run: pnpm run typecheck

      - name: Run tests
        run: pnpm run test

      - name: Build
        run: pnpm run build
